CALIDAD DE CARRETERAS 

aqui se limpiaba la calidad de carreteras

```{r}
library(rio)
CARRE="https://github.com/claudia1006/PROYECTO/raw/master/calidad%20de%20carreteras.xlsx"
ccarre=import(CARRE)
ccarre[,]=lapply(ccarre[,], trimws,whitespace = "[\\h\\v]") # no blanks
names(ccarre)=gsub(" ","",names(ccarre))
```

```{r}
ccarre$Roadquality=as.numeric(ccarre$Roadquality) #UNO SOLO 
```

```{r}
library(stringr)
str_split(ccarre$Country,
                          pattern = '\\s',
                          simplify = T)[,-1]
```

```{r}
ccarre$Country1=str_split(ccarre$Country,
                          pattern = '\\s',
                          simplify = T)[,-1]
#SOLO PASTE 

```

```{r}
str_split(ccarre$Country,
                          pattern = '\\s',
                          simplify = T)[,3]
```

```{r}

ccarre$Country2=str_split(ccarre$Country,
                          pattern = '\\s',
                          simplify = T)[,3]
```

```{r}
str_split(ccarre$Country,
                          pattern = '\\s',
                          simplify = T)[,4]
```

```{r}
ccarre$Country3=str_split(ccarre$Country,
                          pattern = '\\s',
                          simplify = T)[,4]
```


```{r}
library(stringr)
```

```{r}
paste(ccarre$Country1, ccarre$Country2,ccarre$Country3)[1:141]
```

```{r}
ccarre$Countryname=paste(ccarre$Country1, ccarre$Country2,ccarre$Country3)[1:141]

```

```{r}
ccarre$Country=NULL
ccarre$Country1=NULL
ccarre$Country2=NULL
ccarre$Country3=NULL
```

