##Trabajo final

Curso: Estadística para el análisis político 2
Profesor: José Manuel Magallanes Reyes
Integrantes:
  -Gean Pierre Zelaya     20162107
  -Adriano Shimabukuro    20161098
  -Claudia Linares        20171083
  -Alfredo Espinoza       20170552

#Cargar variables.

#ELECTRICIDAD

```{r}
library(rio)
elec="https://github.com/adrianoshimante1998/Trabajo-grupal/raw/master/API_EG.ELC.ACCS.ZS_DS2_en_excel_v2_422316.xls"
electricidad=import(elec)
electricidad[,]=lapply(electricidad[,], trimws,whitespace = "[\\h\\v]") # no blanks
electricidad=na.omit(electricidad)
names(electricidad)=gsub(" ","",names(electricidad)) 
electricidad$Electricity2017=as.numeric(electricidad$Electricity2017) #UNO SOLO 
electricidad=na.omit(electricidad) 
```

#EMPLEO

```{r}
EMPLEO="https://github.com/claudia1006/PROYECTO/raw/master/%25employment.xls"
empleo=import(EMPLEO)
empleo[,]=lapply(empleo[,], trimws,whitespace = "[\\h\\v]") # no blanks
names(empleo)=gsub(" ","",names(empleo)) 
empleo$`%Empleo2017`=as.numeric(empleo$`%Empleo2017`) #UNO SOLO 
empleo=na.omit(empleo) 

```

#COBERTURA DE SALUD 

```{r}
SA="https://github.com/claudia1006/PROYECTO/raw/master/%25%20de%20cobertura%20de%20salud..xlsx"
salud=import(SA)
salud[,]=lapply(salud[,], trimws,whitespace = "[\\h\\v]") # no blanks
names(salud)=gsub(" ","",names(salud)) 
salud$`%decoberturadesalud2017`=as.numeric(salud$`%decoberturadesalud2017`) #UNO SOLO 
salud=na.omit(salud) 
names(salud)[1]="CountryName"
```

#EXPORTACIONES DE BIENES Y SERVICIOS 

```{r}
EX="https://github.com/claudia1006/PROYECTO/raw/master/Exportaciones%20de%20bienes%20y%20servicios%20(%25%20del%20GDP).xls"
expo=import(EX)
expo[,]=lapply(expo[,], trimws,whitespace = "[\\h\\v]") # no blanks
names(expo)=gsub(" ","",names(expo)) 
expo$`Expobienesyservicio%delGDP2017`=as.numeric(expo$`Expobienesyservicio%delGDP2017`) #UNO SOLO 
expo=na.omit(expo) 
```

